# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChemblID', models.CharField(max_length=256)),
                ('Smile', models.CharField(max_length=256)),
                ('mw_freebase', models.FloatField()),
                ('rtb', models.IntegerField()),
                ('Result', models.FloatField()),
                ('Drug', models.BooleanField()),
                ('TAG', models.CharField(max_length=1)),
                ('URL', models.URLField()),
                ('imageURL', models.URLField()),
            ],
        ),
    ]
