# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindthebyte', '0002_auto_20170528_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecule',
            name='Drug',
        ),
    ]
